# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: debian:stretch

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      - run:
          name: Run git pull
          command: |
            git remote add lightsail ec2-user@tech.jongwony.com:ssh_repo.git
            git push lightsail master


      - store_artifacts:
          path: test-reports
          destination: test-reports

      - add_ssh_keys:
          fingerprints:
            - "SHA256:gSWPsIpAs/G1AB7ea6mAwUnezaPwRenRk9p5yCReKP4"
